import type { Metadata } from "next";
import Link from "next/link";
import "./layout.css";
import { Geist } from 'next/font/google'

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const geist = Geist({
    subsets: ['latin'],
})

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={geist.className}>
                <header>
                    <nav>
                        <Link href="/users-csr">Users List (CSR)</Link>
                        <Link href="/users-ssr">Users list (SSR)</Link>
                        <Link href="/parallel">Parallel</Link>
                        <Link href="/dynamic">Dynamic</Link>
                        <Link href="/add-user">Add user</Link>
                        <Link href="/login" className="loginLink">Log in</Link>
                    </nav>
                </header>
                <main>{children}</main>
                <footer>
                    This is a footer for our site
                </footer>
            </body>
        </html>
    );
}
